# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rcollet <rcollet@student.42berlin.de>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/04 12:10:50 by rcollet           #+#    #+#              #
#    Updated: 2026/07/07 13:39:51 by lenivorb         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a

INCL	=	.

HEADERS = libft.h

SRC		=	ft_isalpha.c	ft_isdigit.c	ft_isalnum.c	ft_isascii.c	\
			ft_isprint.c	ft_strlen.c		ft_memset.c		ft_bzero.c		\
			ft_memcpy.c		ft_memmove.c	ft_strlcpy.c	ft_strlcat.c	\
			ft_toupper.c	ft_tolower.c	ft_strchr.c		ft_strrchr.c	\
			ft_strncmp.c	ft_memchr.c		ft_memcmp.c		ft_strnstr.c	\
			ft_atoi.c		ft_calloc.c		ft_strdup.c		ft_substr.c		\
			ft_strjoin.c	ft_strtrim.c	ft_split.c		ft_itoa.c		\
			ft_strmapi.c	ft_striteri.c	ft_putchar_fd.c	ft_putstr_fd.c	\
			ft_putendl_fd.c	ft_putnbr_fd.c	ft_lstnew.c						\
			ft_lstadd_front.c				ft_lstsize.c	ft_lstlast.c	\
			ft_lstadd_back.c				ft_lstdelone.c	ft_lstclear.c	\
			ft_lstiter.c	ft_lstmap.c

OBJ		=	$(SRC:.c=.o)

CCFLAGS	=	-I $(INCL) -Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(OBJ) 
	ar rcs $@ $^

$(OBJ): %.o: %.c $(INCL)/$(HEADERS)
	cc -c $(CCFLAGS) $<

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
